name: assembler
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  libserialport: ^0.3.0+1
  sprintf: ^7.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  collection: ^1.17.0

